### ISSUE TITLE
randomgen changes

### ISSUE THREAD

**Issue by bashtage** [mattip/numpy#18]
@mattip Do you want me to start working on implementing some of the agreed changes? Or are you planning on doing it.  I implemented them in randomgen, it totaled around 2500 line change, so not small.

**Comment by mattip** [comment]
I think I can do it. My goal is to do it over the next couple of days. I realize it is a big invasive change, I will take a look at what you did and reuse the checklist in #17 as well. It also means updating the docs.

We also wanted to deprecate the `np.random.gen` singleton and the `.generator` attribute, those are simpler changes

**Comment by bashtage** [comment]
Here is a more complete list based on what I did to make randomgen like the NumPy API we discussed

- [x] stack allocation inside bit generators, remove from dealloc
- [x] stack allocation in generator and mtrand, remove from dealloc
- [x] remove rand and randn
- [x] rename randint to integers
- [x] remove generator from bit generators
- [x] remove jump 
- [x] Implement jumped, and return a new instance
- [x] remove usemask, set to True
- [x] rename random_sample to random, and have random_sample as a shallow and deprecated version
- [x] Rename RenagomGenerator to Generator
- [x] Remove axis from choice
- [x] Merge patch that adds closed generation to randint (so that it can be used by integers)
- [x] Replace references to brng with either bitgen (for C struct types, e.g, brng_t becomes bitgen_t) or bit_generator for access from classes in Python
- [x] Replace BasicRNG with BitGenerator
- [x] Search and replace 'basic', e.g., 'basic random number generator' becomes 'bit generator'
- [x] Rewrite entropy without code from pcg*
- [x] Remove pgc*, numpy.random.gen

~Edit: more tasks~
~- [ ] refactor most uses of random in tests to use the new API, keep those that require stream compatibility~
~- [ ] document the new API as an alternative in all old API uses~
~- [ ] remove the old code from random._mtrand (alternative: keep it for one version in case something goes wrong)~
- [ ] Update the NEP with the name changes BitGenerator, Generator, integers, random

**Comment by mattip** [comment]
@bashtage I think for `choice` we proposed to do whatever `take` does, no?

**Comment by mattip** [comment]
@rkern please note the tasks above as well as the [discussion summary](https://hackmd.io/OtUbEI_4T06noPYtlLp-4w#Afternoon) which was split off into [this document](https://hackmd.io/E68kqcDZSKyuhmlY0kK3Sg) as well

**Comment by rkern** [comment]
None of those answer my question. What led to the decision to remove PCG at this time? The last I had heard, @bashtage was emailing the PCG author to formalize the license change that she had carried out for the main PCG code. Did we get a negative response? Or no response?

**Comment by mattip** [comment]
No response

**Comment by bashtage** [comment]
I emailed Prof. O’Neill about two weeks ago to make the case for a
licensing change (inclusion in NumPy) and have not received a response.

**Comment by bashtage** [comment]
> @bashtage I think for `choice` we proposed to do whatever `take` does, no?

That is fine with me, and I think it already behaves like this (using `axis=None`)

**Comment by mattip** [comment]
Here is an updated list, after resyncing with randomgen and tweaking much of the documentation.

- [x] Rewrite entropy without code from pcg* - @bashtage could you do this?
- [x] Review that `choice` works like `take` wrt `size` and `axis`
- [ ] Update the NEP with the name changes BitGenerator, Generator, integers, random, jumped

I would like to leave these for a future PR
- [ ] refactor most uses of random in tests to use the new API, keep those that require stream compatibility
- [ ] document the new API as an alternative in all old API uses
Update the NEP with the name changes BitGenerator, Generator, integers, random
- [ ] remove the old code from random._mtrand (alternative: keep it for one version in case something goes wrong)

Not really a NumPy PR but should be done at some point
- [ ] Back-sync the NumPy code to randomgen as much as possible

**Comment by bashtage** [comment]
> could you do this?

Yes

> Back-sync the NumPy code to randomgen as much as possible

This is is mostly done, in the sense that randomgen master looks like the API we discussed (w/o removal of functions like rand)

**Comment by bashtage** [comment]
One more for the lsit

- [x] Bring in recent changes to distribuctions.c that were accepted into NumPy as part of numpy/numpy#13416 . This is small and I can PR this.

**Comment by bashtage** [comment]
I was looking at distributions.c and I think something has not gone quite right.

The lemire method seems to have been removed.  My recollection from the discussion from the sprint was that `Generator` would only use lemire, since this method is generally faster, and that `RandomState` would continue to use the masked generator.  I thought this meant that the `use_masked` option would disappear from `Generator.integers` and it would be set to be false internally. This way `RandomState.randint` could continue to use the same code only with use_masked=True always.

**Comment by bashtage** [comment]
One more I just saw:

- [x] Rename brng_state to bitgen_state

**Comment by mattip** [comment]
> The lemire method seems to have been removed

Whoops, I set the default the wrong way. The task above said "remove usemask, set to True" which I misinterpreted. Please keep reviewing. I will revive Lemire.

**Comment by bashtage** [comment]
There are two choices:

1. Keep both together and set use_maked=True (RS) or False (Gen)
2. Separate these functions, which lets them be simpler, and have masked in legacy_distributions.c and kee lemire in distributions.c

**Comment by bashtage** [comment]
There are still 2 references to PCG64 in the current.  Also, there are some test data values for pcg32 and pcg64 that can be removed.

**Comment by mattip** [comment]
> There are two choices:

I think 2 makes more sense, but will mean more code divergence from randomgen

**Comment by bashtage** [comment]
I can always split it there too...

**Comment by mattip** [comment]
> There are still 2 references to PCG64 in the current. 

Removing from `performance.py` There are mentions in `numpy/random/src/entropy/LICENSE.md`, I can just delete that file, right?

**Comment by bashtage** [comment]
Yes. The current implementation uses the same code from mtrand.pyx that is in numpy 1.16

**Comment by mattip** [comment]
it seems "2 Separate these functions" requires too much code duplication since now we need two copies of bounded_integers.pxd.in and bounded_integers.pyx.in. Now I am trying "1. Keep both together and set use_maked=True (RS) or False (Gen)"

**Comment by bashtage** [comment]
I agree. I did it and it was 500 lines.

**Comment by mattip** [comment]
@bashtage did "closed" become "endpoint"?

**Comment by bashtage** [comment]
Yes, like linspace.

**Comment by mattip** [comment]
hmm. I guess I should change that for numpy from `closed` to `endpoint` already with no deprecation. Also, this line in `generator.pyx`
```
cdef bint _use_masked = use_masked is None or use_masked
```
means the default in generator is `use_masked=True`, but in NumPy we want to use a default of `False`, which is causing test ~failures~ differences between NumPy and randomgen.

Edit: failures -> differences

**Comment by bashtage** [comment]
In randomstate there should be no choice in `randint` and it should be closed=False.

In generator, there should be a choice. I woudl compltel u drop the kwarg use_masked and just have

`cdef bint _use_masked = True # Generator`

**Comment by bashtage** [comment]
No deprecation at all in NumPy since Generator is 100% new there.

**Comment by mattip** [comment]
Understood. ~Currently, in `numpy/random/tests/test_generator_mt19937.py` there are failing tests since in `randomgen` the generator uses `_use_mask = False` but in numpy I want to use `_use_mask = True`. That means I need to adjust the test files and they will diverge between numpy and randomgen.~

Sorry, ignore that

**Comment by mattip** [comment]
@bashtage: After 7c38e2b30 (assuming tests pass) I think all that is left is to update the NEP. My weekend is Fri - Sat, so I will be getting back to this on Sun. I would appreciate a look-through

**Comment by bashtage** [comment]
All done.
